---
sudo: true
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake spec && bundle exec rake lint"
matrix:
  fast_finish: true
  include:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.1.7
      env: PUPPET_GEM_VERSION="~> 4.0"
